version: 2
jobs: 
  build: 
    docker: 
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            rustup component add clippy --toolchain 1.40-x86_64-unknown-linux-gnu
            cargo clippy
      - run:
          name: Formatted
          command: cargo fmt -- --check
      - run:
          name: Build
          command: cargo build --all --release
      - run:
          name: Test
          command: cargo test --all --release